### ISSUE TITLE
Cursor position always changes by 2

### ISSUE THREAD

**Issue by rvanmelle** [kawakamimoeki/baran#16]
I noticed that when splitting text, the chunks have a `cursor` position which changes by length of 2. I had assumed this was meant to point to the character position for the start of the text?

In this block of code:

https://github.com/kawakamimoeki/baran/blob/main/lib/baran/text_splitter.rb#L21C7-L26C10

Is the intention to do `cursor += chunk[:text].length` rather than `cursor += chunk.length` ?

**Comment by moeki0** [comment]
This was a bug. I fixed it #17 . Thank you!

**Comment by moracca** [comment]
I see that this commit was created before the 0.1.11 tag/release, and when I install the gem from rubygems, it installs v0.1.11, however the code doesn't appear to have this issue fixed:

<img width="1069" alt="image" src="https://github.com/kawakamimoeki/baran/assets/7213746/d66a1159-d092-42b1-b21d-aef4d25d3bd3">

Any idea why?

**Comment by moeki0** [comment]
@moracca Sorry, I made a mistake pushing. I have released a new version, please try it.

**Comment by moracca** [comment]
@kawakamimoeki thank you, 0.1.12 is working for me.  Should 0.1.12 be set as the default version on rubygems?
![image](https://github.com/kawakamimoeki/baran/assets/7213746/5e54286e-899e-4a98-bd02-d09708afed32)
