### ISSUE TITLE
Add support for metadata in text chunks

### ISSUE THREAD

**Issue by drale2k** [kawakamimoeki/baran#7]
Hi,

i would like to ask if you would consider adding metadata to text chunks. A example use case would be to store the page number a chunk was extracted from, like a PDF. We started a discussion over at langchainrb about this https://github.com/andreibondarev/langchainrb/issues/318

**Comment by moeki0** [comment]
@drale2k https://github.com/moekidev/baran/pull/8 Will this accomplish our goal?

**Comment by drale2k** [comment]
Looks good to me, thanks!
